version: '3.8'

services:
    mcp:
        image: ghcr.io/sooperset/mcp-atlassian:latest
        container_name: atlas-mcp
        environment:
            JIRA_URL: https://your-domain.atlassian.net
            JIRA_USERNAME: your-jira-user@example.com
            JIRA_API_TOKEN: ${JIRA_API_TOKEN}
            CONFLUENCE_URL: https://your-domain.atlassian.net/wiki
            CONFLUENCE_USERNAME: your-confluence-user@example.com
            CONFLUENCE_API_TOKEN: ${CONFLUENCE_API_TOKEN}
            MCP_VERBOSE: 'true'
            MCP_LOGGING_STDOUT: 'true'
            READ_ONLY_MODE: 'true'
        command: ['--transport', 'sse', '--port', '7000']
        restart: unless-stopped

    mcp-shim:
        image: crackish/mcp-openai-atlassian-proxy:latest
        container_name: atlas-mcp-shim
        environment:
            UPSTREAM_MCP_URL: http://mcp:7000/sse
            JIRA_SHIM_PORT: '7100'
            CONFLUENCE_SHIM_PORT: '7200'
        depends_on:
            - mcp
        restart: unless-stopped

    nginx:
        image: nginx:latest
        container_name: nginx-mcp
        depends_on:
            - mcp
            - mcp-shim
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        restart: unless-stopped

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        entrypoint: >
            sh -c "sleep 10 && certbot certonly --force-renewal --non-interactive --webroot --webroot-path=/var/www/certbot \
            --email admin@example.com --agree-tos --no-eff-email \
            -d your-domain.example || true"
        restart: unless-stopped
# Create a .env file next to this with JIRA_API_TOKEN=... and CONFLUENCE_API_TOKEN=...
