name: Docker Build and Publish

on:
    push:
        branches: ['main']
        tags: ['v*.*.*']
    workflow_dispatch:

jobs:
    docker:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker Hub login
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Compute Docker tags from package.json
              id: vars
              shell: bash
              run: |
                  VERSION=$(jq -r .version package.json)
                  if [[ -z "$VERSION" || "$VERSION" == "null" ]]; then
                    echo "Package version is empty" >&2
                    exit 1
                  fi
                  echo "tags=crackish/mcp-openai-atlassian-proxy:latest,crackish/mcp-openai-atlassian-proxy:v${VERSION}" >> $GITHUB_OUTPUT

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ steps.vars.outputs.tags }}
